## Theory development

In [1]:
import numpy as np

In [34]:
B = np.zeros((3, 3, 2))

B[0][1][1] = 2
B[1][0][1] = 2
B[1][2][1] = 1
B[2][1][1] = 1

B

array([[[ 0.,  0.],
        [ 0.,  2.],
        [ 0.,  0.]],

       [[ 0.,  2.],
        [ 0.,  0.],
        [ 0.,  1.]],

       [[ 0.,  0.],
        [ 0.,  1.],
        [ 0.,  0.]]])

In [35]:
np.sum(B, axis=1)

array([[ 0.,  2.],
       [ 0.,  3.],
       [ 0.,  1.]])

In [23]:
A = np.zeros((B.shape[0], B.shape[2]))

A[0][0] = 1
A[1][0] = 2
A[2][0] = 3

A

array([[ 1.,  0.],
       [ 2.,  0.],
       [ 3.,  0.]])

In [30]:
C = np.zeros((B.shape[0], B.shape[1]))

C[0][0] = 1
C[0][1] = 1
C[1][0] = 1
C[1][1] = 1
C[1][2] = 1
C[2][1] = 1
C[2][2] = 1

C

array([[ 1.,  1.,  0.],
       [ 1.,  1.,  1.],
       [ 0.,  1.,  1.]])

In [43]:
w_in = np.identity((B.shape[2]))
w_in

array([[ 1.,  0.],
       [ 0.,  1.]])

In [59]:
b_in = np.ones((1, B.shape[2]))
b_in[0][1] = 2
b_in

array([[ 1.,  2.]])

In [60]:
A2 = np.dot(np.dot(C, A) + np.sum(B, axis=1), w_in) + b_in
A2

array([[ 4.,  4.],
       [ 7.,  5.],
       [ 6.,  3.]])

In [58]:
l = 5
w_out = np.ones((B.shape[2], l))
w_out

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [61]:
b_out = np.ones((1, l))
b_out

array([[ 1.,  1.,  1.,  1.,  1.]])

In [64]:
s = np.sum(np.dot(A2, w_out) + b_out, axis=0)
s

array([ 32.,  32.,  32.,  32.,  32.])